# Generated by Django 2.1.5 on 2019-01-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackboxonline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackboxroom',
            name='server',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
