# Generated by Django 2.1.5 on 2019-01-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackboxonline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackboxroom',
            name='player_amount',
            field=models.IntegerField(),
        ),
    ]
