# Generated by Django 2.1.5 on 2019-01-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jackboxRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=10)),
                ('game_type', models.CharField(max_length=200)),
                ('app_id', models.CharField(max_length=200)),
                ('player_amount', models.IntegerField(max_length=200)),
                ('audience_amount', models.IntegerField()),
                ('join_able', models.CharField(max_length=100)),
                ('locked', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('online', models.CharField(max_length=100)),
            ],
        ),
    ]
