# Generated by Django 2.1.5 on 2019-01-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackboxonline', '0003_auto_20190121_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackboxroom',
            name='app_id',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jackboxroom',
            name='audience_amount',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='jackboxroom',
            name='game_type',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jackboxroom',
            name='join_able',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jackboxroom',
            name='locked',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jackboxroom',
            name='online',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jackboxroom',
            name='player_amount',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
